version: '3.8'

services:
  web:
    volumes:
      - .:/app:cached
      - /app/node_modules
    command: npm run dev

  api:
    volumes:
      - ./backend/app:/app
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
