services:
  web:
    build:
      context: .
      args:
        API_SERVER: ${API_SERVER}
        NEXT_PUBLIC_API_BROWSER: ${NEXT_PUBLIC_API_BROWSER}
        NEXT_PUBLIC_AWS_S3_BUCKET: ${NEXT_PUBLIC_AWS_S3_BUCKET}
    container_name: nextjs-app
    ports:
      - "3000:3000"
    env_file:
      - ${ENV_FILE:-.env.local}
    depends_on:
      # - api
      api:
        condition: service_healthy

  api:
    build:
      context: ./backend
    container_name: fastapi-app
    ports:
      - "8000:8000"
    volumes:
      - ./backend/app:/app
    env_file:
      - ${ENV_FILE:-.env.local}
    healthcheck:
      # test: ["CMD", "wget", "--spider", "-q", "http://localhost:8000/api/posts"]
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/posts"]
      interval: 10s
      timeout: 5s
      retries: 5
      # disable: true

volumes:
  mongo_data:
