version: "3.8"

services:
  web:
    build: .
    container_name: nextjs-app
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://api:8000
      - NEXT_PUBLIC_IS_DOCKER=true
      - NEXT_PUBLIC_API_DOCKER=http://api:8000
      - NEXT_PUBLIC_API_LOCAL=http://localhost:8000
    depends_on:
      - api

  api:
    build:
      context: ./backend
    container_name: fastapi-app
    ports:
      - "8000:8000"
    volumes:
      - ./backend/app:/app
    env_file:
      - .env.local

volumes:
  mongo_data:
