version: "3.8"

services:
  web:
    build: .
    container_name: nextjs-app
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://api:8000
      - NEXT_PUBLIC_IS_DOCKER=true
      - NEXT_PUBLIC_API_DOCKER=http://api:8000
      - NEXT_PUBLIC_API_LOCAL=http://localhost:8000
    depends_on:
      - api

  api:
    build:
      context: ./backend
    container_name: fastapi-app
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    environment:
      - MAILGUN_API_KEY
      - MAILGUN_DOMAIN
      - MAILGUN_FROM
      - MAILGUN_TO
    depends_on:
      - mongo

  mongo:
    image: mongo:6.0
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
