[mypy]
python_version = 3.11
ignore_missing_imports = true
disallow_untyped_defs = true
check_untyped_defs = true

[mypy-bleach]
ignore_missing_imports = true

[mypy-requests]
ignore_missing_imports = true
