name: Deploy to DigitalOcean

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Clone repo
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Generate .env.production from secret
      - name: Generate .env.production from secret
        run: |
          echo "${{ secrets.ENV_PRODUCTION }}" > .env.production

      # Step 3: Copy app files to DigitalOcean
      - name: Copy app files to DigitalOcean
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.DO_HOST }}
          username: ${{ secrets.DO_USER }}
          key: ${{ secrets.DO_SSH_KEY }}
          source: |
            ./*
            .env.production
          target: "~/app"

      # Step 4: SSH into server and deploy
      - name: SSH and deploy
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.DO_HOST }}
          username: ${{ secrets.DO_USER }}
          key: ${{ secrets.DO_SSH_KEY }}
          script: |
            cd ~/app

            echo "Starting fresh deployment..."

            # Ensure Docker is clean
            docker compose down --volumes --remove-orphans || true

            # Build and start all containers with the correct env file
            docker compose --env-file .env.production up -d --build

            # Verify containers are running
            docker ps
